# https://docs.spring.io/spring-boot/docs/2.0.4.RELEASE/reference/htmlsingle/#common-application-properties \u5177\u4F53\u914D\u7F6E
server:
  port: 8080



# \u6570\u636E\u6E90
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ubun?characterEncoding=UTF8&amp;serverTimezone=UTC
    username: root
    password: root
    driver-class-name : com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


mybatis:
  config-location: classpath:mybatis/config/mybatis.cfg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml