# https://docs.spring.io/spring-boot/docs/2.0.4.RELEASE/reference/htmlsingle/#common-application-properties \u5177\u4F53\u914D\u7F6E
server:
  port: 8080
  servlet:
    context-path: /



# \u6570\u636E\u6E90
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ubun?characterEncoding=UTF8&amp;serverTimezone=UTC
    username: root
    password: root
    driver-class-name : com.mysql.jdbc.Driver
    minIdle: 5
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: stat # ,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
    druidLoginName: wjf # 登录druid的账号
    druidPassword: wjf # 登录druid的密码


  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html


  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main/java
      exclude: WEB-INF/*

mybatis:
  config-location: classpath:mybatis/config/mybatis.cfg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml