# https://docs.spring.io/spring-boot/docs/2.0.4.RELEASE/reference/htmlsingle/#common-application-properties \u5177\u4F53\u914D\u7F6E
server:
  port: 8080
  servlet:
    context-path: /



# \u6570\u636E\u6E90
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ubun?characterEncoding=UTF8&amp;serverTimezone=UTC
    username: root
    password: root
    driver-class-name : com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

mybatis:
  config-location: classpath:mybatis/config/mybatis.cfg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml